# -*- coding: utf-8 -*-
"""Bank Customer Complaint Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x3CDbbPSF8PBHxfg1wAgB1zADp_D5_9f
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

df=pd.read_csv("/content/drive/MyDrive/CSV/complaints.csv")
df.head()


df.rename(columns={'Unnamed: 0': 'Complaint_No'}, inplace=True)
df.head()

unique=df["product"].unique()
unique

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x='product', data=df)
plt.title('Distribution of Complaints by Product')
plt.xticks(rotation=45)  # Rotate x-axis labels for better visibility
plt.show()

#----------
#----------

df['narrative_length'] = df['narrative'].apply(lambda x: len(str(x)) if pd.notnull(x) else 0)
sns.histplot(df['narrative_length'])
plt.title('Distribution of Narrative Lengths')
plt.xticks(rotation=45)  # Rotate x-axis labels for better visibility
plt.show()


df_encoded = pd.get_dummies(df['product'])
df = pd.concat([df, df_encoded], axis=1)
df.head()
df = df.drop('product', axis=1)
df.head()
df.info()
df.isnull().sum()

df=df.dropna()
df.isnull().sum()
df.duplicated().sum()

import seaborn as sns
import matplotlib.pyplot as plt

df_melted = pd.melt(df, value_vars=["credit_card", "credit_reporting", "debt_collection", "mortgages_and_loans", "retail_banking"])

df_melted["value"] = df_melted["value"].astype(bool)

#-------
plt.figure(figsize=(10, 6))
sns.set(style="whitegrid")
ax = sns.countplot(x="variable", hue="value", data=df_melted)

#-------
ax.set(xlabel="Categories", ylabel="Count", title="Count of True and False for Each Category")
plt.xticks(rotation=45)  # Rotate x-axis labels for better visibility
plt.show()